// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyB2HXqeMwPq8ypid0D5tEvGcLMIp7Jf-c0",
      authDomain: "imdf-c3ec7.firebaseapp.com",
      databaseURL: "https://imdf-c3ec7-default-rtdb.firebaseio.com",
      projectId: "imdf-c3ec7",
      storageBucket: "imdf-c3ec7.appspot.com",
      messagingSenderId: "821110126310",
      appId: "1:821110126310:web:eae18953e8f2d0e3ff2d27");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyB2HXqeMwPq8ypid0D5tEvGcLMIp7Jf-c0",
      authDomain: "imdf-c3ec7.firebaseapp.com",
      databaseURL: "https://imdf-c3ec7-default-rtdb.firebaseio.com",
      projectId: "imdf-c3ec7",
      storageBucket: "imdf-c3ec7.appspot.com",
      messagingSenderId: "821110126310",
      appId: "1:821110126310:web:eae18953e8f2d0e3ff2d27");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyB2HXqeMwPq8ypid0D5tEvGcLMIp7Jf-c0",
    authDomain: "imdf-c3ec7.firebaseapp.com",
    databaseURL: "https://imdf-c3ec7-default-rtdb.firebaseio.com",
    projectId: "imdf-c3ec7",
    storageBucket: "imdf-c3ec7.appspot.com",
    messagingSenderId: "821110126310",
    appId: "1:821110126310:web:eae18953e8f2d0e3ff2d27",
    iosClientId:
        '599030350718-rt5diuiggpna5fmco6k05teqm2km0f66.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyB2HXqeMwPq8ypid0D5tEvGcLMIp7Jf-c0",
    authDomain: "imdf-c3ec7.firebaseapp.com",
    databaseURL: "https://imdf-c3ec7-default-rtdb.firebaseio.com",
    projectId: "imdf-c3ec7",
    storageBucket: "imdf-c3ec7.appspot.com",
    messagingSenderId: "821110126310",
    appId: "1:821110126310:web:eae18953e8f2d0e3ff2d27",
    iosClientId:
        '599030350718-rt5diuiggpna5fmco6k05teqm2km0f66.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );
}
